name: Run Tests (Microsoft Windows)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.10-release
          tag: 5.10-RELEASE
      - uses: actions/checkout@v4
      - name: ğŸ’€ Install winget
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
      - name: ğŸ”¥ Upgrade MSVC for a working STL
        shell: pwsh
        run: winget upgrade --all --accept-source-agreements --accept-package-agreements
      - name: ğŸ™ Fetch Git Submodules
        run: git submodule update --init --recursive
      - name: ğŸ§ª Test
        run: swift test
